import { useState } from 'react'
import { Activity, Bell, ChevronDown, CircleHelp, LayoutDashboard, Map, Menu, Settings, UserRound, Users, X } from 'lucide-react'
import { copy } from './i18n'
import { useHeatmapData } from './features/heatmap/hooks/useHeatmapData'
import AreaHeatmap from './features/heatmap/components/AreaHeatmap'
import { useAnomalies } from './features/anomalies/hooks/useAnomalies'
import AnomalyTable from './features/anomalies/components/AnomalyTable'
import EvidenceDrawer from './features/evidence/components/EvidenceDrawer'
import { useLiquidityForecast } from './features/forecasts/hooks/useLiquidityForecast'
import LiquidityForecastChart from './features/forecasts/components/LiquidityForecastChart'
import '../../ops-portal/src/styles/ops-theme.css'

const nav = [['overview', LayoutDashboard], ['map', Map], ['anomalies', Bell], ['forecast', Activity], ['agents', Users], ['settings', Settings], ['help', CircleHelp]]
const card = 'rounded-2xl border border-slate-200 bg-white shadow-card'

function RiskWorkspace({ onSwitchRole }) {
  const [lang, setLang] = useState(() => localStorage.getItem('risk_lang') || 'en'); const [view, setView] = useState('overview'); const [menu, setMenu] = useState(false); const [profile, setProfile] = useState(false); const [selected, setSelected] = useState(null); const [filters, setFilters] = useState({ area: 'All', provider: 'All', agent: 'All', time: 'All' })
  const t = copy[lang]; const bn = lang === 'bn'; const heat = useHeatmapData(); const anomalies = useAnomalies(); const forecast = useLiquidityForecast(); const areas = heat.data || []; const allItems = anomalies.data || []
  const items = allItems.filter((item) => (filters.area === 'All' || item.area === filters.area) && (filters.provider === 'All' || item.provider === filters.provider) && (filters.agent === 'All' || item.agent === filters.agent) && (filters.time === 'All' || item.timeBucket === filters.time))
  const change = () => { const next = bn ? 'en' : 'bn'; setLang(next); localStorage.setItem('risk_lang', next); document.documentElement.lang = next }
  const go = (id) => { setView(id); setMenu(false) }
  return <div className="min-h-screen"><header className="fixed inset-x-0 top-0 z-40 flex h-[70px] items-center border-b border-slate-200 bg-white px-4 lg:px-7"><button className="mr-3 lg:hidden" onClick={() => setMenu(true)} aria-label="Open menu"><Menu/></button><button onClick={() => go('overview')} className="flex items-center gap-2 lg:w-[220px]" aria-label="Shahajjo risk home"><span className="grid size-9 place-items-center rounded-xl bg-brand font-bold text-white">স</span><b className="text-lg">{t.brand}</b></button><div className="ml-auto flex items-center gap-2"><button onClick={change} className="rounded-lg px-3 py-2 text-xs font-bold text-brand"><span className={!bn ? '' : 'opacity-40'}>EN</span><span className="px-1 text-slate-300">|</span><span className={bn ? '' : 'opacity-40'}>বাংলা</span></button><div className="relative"><button onClick={() => setProfile(!profile)} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold"><UserRound className="size-4"/>Risk analyst<ChevronDown className="size-3"/></button>{profile && <div className="absolute right-0 top-12 w-56 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><div className="px-3 py-2"><b className="text-sm">Farzana Akter</b><p className="text-xs text-slate-400">Dhaka North</p></div><button onClick={onSwitchRole} className="w-full rounded-xl px-3 py-2 text-left text-xs font-bold hover:bg-slate-50">Switch role / workspace</button></div>}</div></div></header>
    <aside className={`fixed bottom-0 left-0 top-0 z-50 w-[240px] border-r border-slate-200 bg-white p-4 transition lg:top-[70px] lg:z-30 lg:w-[220px] lg:translate-x-0 ${menu ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-8 flex justify-end lg:hidden"><button onClick={() => setMenu(false)}><X/></button></div><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-widest text-slate-400">Risk workspace</p><nav className="space-y-1">{nav.map(([id, Icon]) => <button key={id} onClick={() => go(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${view === id ? 'bg-brand/10 text-brand' : 'text-slate-500 hover:bg-slate-50'}`}><Icon className="size-[18px]"/>{id === 'help' ? 'Help & FAQ' : t[id]}</button>)}</nav><div className="absolute bottom-5 left-4 right-4 rounded-xl bg-slate-50 p-3 text-xs"><b>Farzana Akter</b><p className="text-slate-400">Dhaka North</p></div></aside>{menu && <button className="fixed inset-0 z-40 bg-black/20 lg:hidden" onClick={() => setMenu(false)}/>}<main className="pt-[70px] lg:pl-[220px]"><div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><div className="mb-6"><h1 className="text-2xl font-bold">{view === 'help' ? 'Help & operating guidance' : t.title}</h1><p className="mt-1 text-sm text-slate-500">{view === 'help' ? 'Quick answers for the risk review workflow.' : t.subtitle}</p></div>
      {['overview', 'anomalies'].includes(view) && <Filters items={allItems} value={filters} onChange={setFilters}/>}
      {view === 'overview' && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[t.healthy, '119', '+4', 'text-emerald-600'], [t.review, '21', '-2', 'text-amber-600'], [t.critical, '8', '+1', 'text-red-600'], [t.response, '8m', '-3m', 'text-emerald-600']].map(([label, value, hint, tone]) => <section key={label} className={`${card} p-5`}><p className="text-sm text-slate-500">{label}</p><div className="mt-3 flex items-end justify-between"><b className="text-3xl">{value}</b><span className={`text-xs font-bold ${tone}`}>{hint}</span></div></section>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><section className={`${card} p-5`}><h2 className="font-bold">{t.riskMap}</h2><p className="text-xs text-slate-500">{t.riskMapHint}</p><AreaHeatmap areas={areas} selected={null} onSelect={(area) => setFilters({ ...filters, area: area.name })} bn={bn}/></section><section className={`${card} p-5`}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{t.liquidity}</h2><p className="text-xs text-slate-500">{t.liquidityHint}</p></div><div className="flex gap-2"><span className="h-fit rounded-lg bg-orange-100 px-2 py-1 text-xs font-bold text-orange-800">Nagad · ~3hrs to shortage</span><span className="h-fit rounded-lg bg-slate-50 px-2 py-1 text-xs font-bold">{forecast.data?.confidence}% confidence</span></div></div><LiquidityForecastChart data={forecast.data}/></section></div><section className={`${card} mt-5 p-5`}><h2 className="mb-4 font-bold">{t.anomalyFeed}</h2><AnomalyTable items={items} onSelect={setSelected} bn={bn}/></section></>}
      {view === 'map' && <section className={`${card} p-5`}><h2 className="font-bold">{t.riskMap}</h2><AreaHeatmap areas={areas} selected={null} onSelect={(area) => { setFilters({ ...filters, area: area.name }); go('anomalies') }} bn={bn}/></section>}{view === 'anomalies' && <section className={`${card} p-5`}><AnomalyTable items={items} onSelect={setSelected} bn={bn}/></section>}{view === 'forecast' && <section className={`${card} p-5`}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{t.liquidity}</h2><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-bold text-orange-800">Nagad · ~3hrs to shortage</span></div><LiquidityForecastChart data={forecast.data}/></section>}{view === 'agents' && <section className={`${card} p-5`}><h2 className="font-bold">{t.agents}</h2><p className="mt-3 text-sm text-slate-500">148 outlets · 119 healthy · 29 require review</p></section>}{view === 'settings' && <section className={`${card} max-w-2xl p-5`}>{['Critical risk notifications', 'Provider feed quality alerts', 'Daily area summary'].map((item, index) => <label key={item} className="flex justify-between border-b border-slate-100 py-4 last:border-0">{item}<input type="checkbox" defaultChecked={index < 2} className="accent-brand"/></label>)}</section>}{view === 'help' && <Help/>}</div></main><EvidenceDrawer item={selected} onClose={() => setSelected(null)} bn={bn} text={t}/></div>
}

function Filters({ items, value, onChange }) {
  const values = (key) => ['All', ...new Set(items.map((item) => item[key]).filter(Boolean))]
  return <div className="mb-5 flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-card">{[['provider', 'Provider'], ['agent', 'Agent'], ['area', 'Area']].map(([key, label]) => <label key={key} className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}<select value={value[key]} onChange={(event) => onChange({ ...value, [key]: event.target.value })} className="mt-1 block min-w-32 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700">{values(key).map((item) => <option key={item}>{item}</option>)}</select></label>)}<label className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Time<select value={value.time} onChange={(event) => onChange({ ...value, time: event.target.value })} className="mt-1 block min-w-32 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700"><option value="All">Any time</option><option value="1h">Last hour</option></select></label><button onClick={() => onChange({ area: 'All', provider: 'All', agent: 'All', time: 'All' })} className="ml-auto self-end rounded-xl px-3 py-2 text-xs font-bold text-brand">Clear filters</button></div>
}

function Help() { return <div className="grid gap-4 lg:grid-cols-2"><section className={`${card} p-5`}><h2 className="font-bold">How should I read confidence?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Lower confidence means data may be delayed or conflicting. Verify the provider record before escalating.</p></section><section className={`${card} p-5`}><h2 className="font-bold">What does “unusual” mean?</h2><p className="mt-2 text-sm leading-6 text-slate-500">It means the pattern requires review, not that a judgment is final. A human reviewer makes the decision.</p></section><section className={`${card} p-5`}><h2 className="font-bold">Who owns an alert?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Open the evidence panel to see the assignee, status, next step, and full audit history.</p></section></div> }

export default function App(props) {
  return <div className="dashboard-wave dashboard-wave--risk"><RiskWorkspace {...props}/></div>
}
