import { Clock3, UserRoundCheck, X } from 'lucide-react'
import ConfidenceScoreBadge from './ConfidenceScoreBadge'
import ShapWaterfallChart from './ShapWaterfallChart'

const stages = ['Detected', 'Assigned', 'Acknowledged', 'Human review', 'Resolved']

export default function EvidenceDrawer({ item, onClose, bn = false, text }) {
  if (!item) return null
  return <><button className="fixed inset-0 z-40 bg-slate-950/20" onClick={onClose} aria-label="Close evidence"/><aside className="fixed bottom-0 right-0 top-0 z-50 w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><button onClick={onClose} className="absolute right-5 top-5"><X className="size-5"/></button><p className="text-xs font-bold text-brand">{item.id}</p><h2 className="mt-2 pr-8 text-xl font-bold">{bn ? item.titleBn : item.title}</h2><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-500">{item.area} · {item.provider}<ConfidenceScoreBadge score={item.confidence}/></div><div className="mt-5 flex flex-wrap gap-2"><span className="flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold"><UserRoundCheck className="size-3"/>{item.owner}</span><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-800">{item.status}</span></div><section className="mt-5 rounded-2xl bg-slate-50 p-4"><h3 className="text-xs font-bold uppercase text-slate-400">{text.evidence}</h3><p className="mt-2 text-sm leading-6">{bn ? item.evidenceBn : item.evidence}</p></section><section className="mt-5"><h3 className="mb-4 text-sm font-bold">{text.why}</h3><ShapWaterfallChart/></section><section className="mt-6 rounded-2xl border border-brand/20 p-4"><h3 className="text-xs font-bold text-brand">{text.safeStep}</h3><p className="mt-2 text-sm leading-6">{bn ? item.actionBn : item.action}</p></section><section className="mt-6"><h3 className="text-sm font-bold">Review progress</h3><AlertProgress currentStep={item.currentStep ?? 3}/><h3 className="mt-5 text-sm font-bold">Audit history</h3><div className="mt-3 border-l-2 border-slate-200 pl-4">{item.history?.map((event) => <p key={event} className="flex items-center gap-2 py-2 text-xs text-slate-500"><Clock3 className="size-3"/>{event}</p>)}</div><p className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs font-semibold text-slate-700"><b>Final outcome:</b> {item.finalStatus || 'Not finalized — human review pending'}</p></section></aside></>
}

function AlertProgress({ currentStep }) { return <div className="relative mt-4 flex justify-between"><span className="absolute left-3 right-3 top-2.5 h-0.5 bg-slate-200"/>{stages.map((stage, index) => <div key={stage} className="relative z-10 flex w-1/5 flex-col items-center text-center"><span className={`grid size-5 place-items-center rounded-full border-2 text-[9px] font-bold ${index <= currentStep ? 'border-brand bg-brand text-white' : 'border-slate-300 bg-white text-slate-400'}`}>{index < currentStep ? '✓' : index + 1}</span><span className={`mt-1 text-[9px] font-semibold leading-3 ${index <= currentStep ? 'text-slate-700' : 'text-slate-400'}`}>{stage}</span></div>)}</div> }
