import { useState } from 'react'
import { Bell,Home,LogOut,RefreshCw,UserRound,WalletCards } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import LoginForm from './features/auth/components/LoginForm'
import { useAuth } from './features/auth/hooks/useAuth'
import { useUnifiedBalance,demoBalance } from './features/balance/hooks/useUnifiedBalance'
import BalanceCard from './features/balance/components/BalanceCard'
import BalanceHistoryChart from './features/balance/components/BalanceHistoryChart'
import AlertList from './features/alerts/components/AlertList'
import AlertToast from './features/alerts/components/AlertToast'
import { useRealtimeAlerts } from './features/alerts/hooks/useRealtimeAlerts'
import BalanceRoute from './routes/BalanceRoute'

const money=n=>new Intl.NumberFormat('bn-BD',{maximumFractionDigits:0}).format(n)
export default function App(){const{t,i18n}=useTranslation();const{user,login,logout}=useAuth();const[tab,setTab]=useState('overview');const balanceQuery=useUnifiedBalance(user?.id||'AGT-2048');const balance=balanceQuery.data||demoBalance;const{alerts,latest,clearLatest}=useRealtimeAlerts();if(!user)return <LoginForm onLogin={login}/>;const changeLanguage=()=>{const next=i18n.language==='bn'?'en':'bn';i18n.changeLanguage(next);localStorage.setItem('shahajjo_language',next);document.documentElement.lang=next};return <div className="min-h-screen pb-24 lg:pb-8">
  <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95"><div className="mx-auto flex h-16 max-w-6xl items-center px-4"><div className="grid size-9 place-items-center rounded-xl bg-brand text-lg font-bold text-white">স</div><span className="ml-2 text-lg font-bold">{t('brand')}</span><div className="ml-auto flex items-center gap-2"><button onClick={changeLanguage} className="rounded-lg px-3 py-2 text-xs font-bold text-brand">{i18n.language==='bn'?'EN':'বাং'}</button><button onClick={()=>balanceQuery.refetch()} className="grid size-9 place-items-center rounded-xl border border-slate-200" aria-label={t('sync')}><RefreshCw className={`size-4 ${balanceQuery.isFetching?'animate-spin':''}`}/></button><button onClick={logout} className="hidden size-9 place-items-center rounded-xl border border-slate-200 sm:grid" aria-label={t('logout')}><LogOut className="size-4"/></button></div></div></header>
  <main className="mx-auto max-w-6xl p-4 sm:p-6">{tab==='overview'&&<><div className="mb-6"><p className="text-sm text-slate-500">{t('greeting')}, {user.name}</p><h1 className="mt-1 text-2xl font-bold">{t('outlet')}</h1><p className="mt-1 flex items-center gap-2 text-sm text-emerald-700"><i className="size-2 rounded-full bg-emerald-500"/>{t('status')}</p></div><section className="rounded-3xl bg-slate-900 p-5 text-white sm:p-6"><p className="text-xs text-slate-300">{t('totalLiquidity')}</p><p className="mt-2 text-3xl font-bold">৳{money(balance.total)}</p><div className="mt-5 grid grid-cols-3 gap-3 border-t border-white/10 pt-4 text-xs"><div><span className="text-slate-400">{t('sharedCash')}</span><b className="mt-1 block">৳{money(balance.cash)}</b></div><div><span className="text-slate-400">{t('cashIn')}</span><b className="mt-1 block text-emerald-400">৳{money(balance.cashIn)}</b></div><div><span className="text-slate-400">{t('cashOut')}</span><b className="mt-1 block text-orange-300">৳{money(balance.cashOut)}</b></div></div></section><h2 className="mb-3 mt-7 font-bold">{t('providerBalances')}</h2><div className="grid gap-3 sm:grid-cols-3">{balance.providers.map(p=><BalanceCard key={p.id} item={p}/>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[3fr_2fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><h2 className="font-bold">{t('continuity')}</h2><p className="text-xs text-slate-500">{t('continuityHint')}</p><BalanceHistoryChart/></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="mb-4 flex justify-between"><h2 className="font-bold">{t('activeAlerts')}</h2><button onClick={()=>setTab('alerts')} className="text-xs font-bold text-brand">{t('viewAll')}</button></div><AlertList alerts={alerts.slice(0,2)}/></section></div></>}
  {tab==='balance'&&<BalanceRoute balance={balance}/>} {tab==='alerts'&&<><h1 className="mb-5 text-2xl font-bold">{t('alerts')}</h1><section className="rounded-2xl border border-slate-200 bg-white p-5"><AlertList alerts={alerts}/></section></>} {tab==='profile'&&<><h1 className="text-2xl font-bold">{t('profile')}</h1><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><p className="font-bold">{user.name}</p><p className="text-sm text-slate-500">{user.phone}</p><button onClick={logout} className="mt-6 rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-600">{t('logout')}</button></section></>}</main>
  <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-4 border-t border-slate-200 bg-white px-2 pb-[env(safe-area-inset-bottom)] lg:left-1/2 lg:bottom-5 lg:max-w-md lg:-translate-x-1/2 lg:rounded-2xl lg:border lg:shadow-lg">{[["overview",Home,'overview'],['balance',WalletCards,'balance'],['alerts',Bell,'alerts'],['profile',UserRound,'profile']].map(([id,Icon,key])=><button key={id} onClick={()=>setTab(id)} className={`flex flex-col items-center gap-1 py-3 text-[10px] font-semibold ${tab===id?'text-brand':'text-slate-400'}`}><Icon className="size-5"/>{t(key)}</button>)}</nav><AlertToast alert={latest} onClose={clearLatest}/>
  </div>}
